#!/bin/bash

set -e

[[ -d ".venv" ]] || {
  printf "Seems that you did not set up this project yet. Check out how to do it in \033[32mREADME.md\033[0m\n";
  exit 1;
}

[[ -x "$(command -v python3)" ]] || {
  printf "\033[1m\033[41m\033[39mPython not found!\n\033[0m";
  printf "Please, install the python3 and configure this project. Check out how to do it in \033[32mREADME.md\033[0m\n";
  exit 1;
}

source .venv/bin/activate
python3 src/main.py $@
